version: '3'
services:
  matcher:
    image: fluxfederation/pumpkin-pumpkin-matcher
    environment:
      PGUSER: postgres
      PGPASSWORD: topsecret
      PGHOST: db
  server:
    image: fluxfederation/pumpkin-pumpkin-server
    environment:
      PGUSER: postgres
      PGPASSWORD: topsecret
      PGHOST: db
      AUTH_TOKEN: test
    ports:
      - "8080:8080"
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: topsecret
    ports:
      - "65432:5432"

